Repository Vibe-Code-Agent/create-pull-request, pull requests merged in 2025-10, with the labels that each got.

#82 Update prompt include confluence page content
  README.md
  lib/commands/create-pr.d.ts.map
  lib/commands/create-pr.js
  lib/commands/create-pr.js.map
  lib/constants/index.d.ts
  lib/constants/index.d.ts.map
  lib/constants/index.js
  lib/constants/index.js.map
  lib/services/ai-description-generator.d.ts.map
  lib/services/ai-description-generator.js
  lib/services/ai-description-generator.js.map
  lib/services/jira.d.ts
  lib/services/jira.d.ts.map
  lib/services/jira.js
  lib/services/jira.js.map
  lib/utils/spinner.d.ts.map
  lib/utils/spinner.js
  lib/utils/spinner.js.map
  lib/utils/validation.d.ts.map
  lib/utils/validation.js
  lib/utils/validation.js.map
  src/__tests__/ai-description-generator.test.ts
  src/__tests__/jira.test.ts
  src/__tests__/spinner.test.ts
  src/commands/create-pr.ts
  src/constants/index.ts
  src/services/ai-description-generator.ts
  src/services/jira.ts
  src/utils/spinner.ts
  src/utils/validation.ts
Labels: breaking

#88 Update to fix issue
  lib/services/ai-providers/response-parser.d.ts
  lib/services/ai-providers/response-parser.d.ts.map
  lib/services/ai-providers/response-parser.js
  lib/services/ai-providers/response-parser.js.map
  lib/services/atlassian-facade.js
  lib/services/atlassian-facade.js.map
  lib/services/atlassian/confluence.d.ts
  lib/services/atlassian/confluence.d.ts.map
  lib/services/atlassian/confluence.js
  lib/services/atlassian/confluence.js.map
  lib/services/atlassian/jira.d.ts.map
  lib/services/atlassian/jira.js
  lib/services/atlassian/jira.js.map
  src/__tests__/ai-providers/response-parser.test.ts
  src/__tests__/atlassian-facade.test.ts
  src/__tests__/atlassian/confluence.test.ts
  src/services/ai-providers/response-parser.ts
  src/services/atlassian-facade.ts
  src/services/atlassian/confluence.ts
  src/services/atlassian/jira.ts
Labels: bugfix

#94 Consolidates SonarCloud analysis into CI workflow
  .github/CODEOWNERS
  .github/GITHUB_ACTIONS.md
  .github/workflows/auto-version.yml
  .github/workflows/cache-cleanup.yml
  .github/workflows/ci.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/sonarcloud.yml
Labels: bugfix

#96 🏷️ Auto version update to v3.0.6
  package-lock.json
  package.json
Labels: automated, version-update

#102 🏷️ Auto version update to v3.0.9
  package-lock.json
  package.json
Labels: automated, version-update

#115 Fix git extension
  git-create-pr
  lib/index.js
  lib/index.js.map
  scripts/setup-env.js
  scripts/setup-git-extension.js
  src/__tests__/index.test.ts
  src/index.ts
Labels: bugfix

#120 🏷️ Auto version update to v3.0.15
  package-lock.json
  package.json
Labels: automated, version-update
